---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates Windows IIS Web Server
Parameters:
  InstanceName:
    Description: The name of the instance used for tagging.  Also used as the hostname.
    Type: String
  SubnetId:
    Description: Subnet for the instance
    Type: AWS::EC2::Subnet::Id
  KeyName:
    Description: EC2 Key Pair
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyName.
  Environment:
    Description: Environment Name
    Type: String
    Default: Production
  InstanceType:
    Description: >-
      Specify a valid EC2 instance type. Use new generation instance types where possible. For a list of instance types: https://aws.amazon.com/ec2/instance-types/
    Type: String
    Default: t2.medium
  ImageId:
    Description: >-
      Specify an Image ID to use. NOTE: The default AMI is for Microsoft Windows Server 2019 Base
    Type: AWS::EC2::Image::Id
    Default: ami-0204606704df03e7e
  SecurityGroupIDs:
    Description: Specify any security groups (by SG ID) that need to be attached to the instance. Comma separated list.'
    Type: List<AWS::EC2::SecurityGroup::Id>
    Default: None
  RootVolumeSize:
    Description: 'In GiB,how big of a root volume is required for the instance?'
    Default: '30'
    Type: Number
Resources:
  IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: POC-IIS-Webserver
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:CreateTags'
                  - 'ec2:Describe*'
                  - 's3:List*'
                  - 's3:Get*'
                  - 's3:*'
                  - 'ssm:*'
                Resource: '*'
  IAMProfile:
    Type: 'AWS::IAM::InstanceProfile'
    DependsOn:
      - IAMRole
    Properties:
      Path: /
      Roles:
       - Ref: IAMRole
  WebServer:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            C:\Users\Administrator\windows_iis_base.ps1: 
              source: https://s3.amazonaws.com/cloudticity-connectathon-public/windows_iis_base.ps1
          commands:
            1-windows-iis-base:
              command: powershell C:\Users\Administrator\windows_iis_base.ps1
              waitAfterCompletion: forever
    Properties:
      InstanceType:
        Ref: InstanceType
      ImageId:
        Ref: ImageId
      SecurityGroupIds:
        Ref: SecurityGroupIDs
      KeyName:
        Ref: KeyName
      SubnetId:
        Ref: SubnetId
      Tags:
        -
          Key: Name
          Value: 
            Ref: InstanceName
      IamInstanceProfile: 
        Ref: IAMProfile
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 
              Ref: RootVolumeSize
            VolumeType: gp2
      UserData:
        Fn::Base64:
          Fn::Join:
          - ''
          - - "<script>\n"
            - 'cfn-init.exe -v -s '
            - Ref: AWS::StackId
            - " -r WebServer"
            - " --region "
            - Ref: AWS::Region
            - "\n"
            - "</script>"